// Uncharted Expedition — seed data shared by the in-memory store and the
// MongoDB store (seeded once when both collections are empty).

import { FeedbackEntry, ExpeditionUser } from './models';

export const ALL_PRODUCT_IDS = [
  // Lab 502 (10)
  '502-01', '502-02', '502-03', '502-04', '502-05', '502-06', '502-07', '502-08', '502-09', '502-10',
  // Lab 508 (6)
  '508-01', '508-02', '508-03', '508-04', '508-05', '508-06',
  // Lab 509 (10)
  '509-01', '509-02', '509-03', '509-04', '509-05', '509-06', '509-07', '509-08', '509-09', '509-10',
  // Lab 510 (4)
  '510-01', '510-02', '510-03', '510-04',
];

export const defaultUsers: ExpeditionUser[] = [
  {
    email: 'aarav.sharma@techx.vcet.edu.in',
    name: 'Aarav Sharma',
    department: 'AI-DS',
    completedProducts: [...ALL_PRODUCT_IDS],
    unlockedLabs: ['a', 'c', 'd', 'e'],
    completedLabs: ['a', 'c', 'd', 'e'],
    shards: ['a', 'c', 'd', 'e'],
    discoveredClues: ['clue-a-1'],
    discoveredTreasures: ['tr-coin'],
  },
  {
    email: 'diya.patel@techx.vcet.edu.in',
    name: 'Diya Patel',
    department: 'COMPS',
    completedProducts: [...ALL_PRODUCT_IDS],
    unlockedLabs: ['a', 'c', 'd', 'e'],
    completedLabs: ['a', 'c', 'd', 'e'],
    shards: ['a', 'c', 'd', 'e'],
    discoveredClues: ['clue-a-2'],
    discoveredTreasures: ['tr-relic'],
  },
  {
    email: 'rohan.mehta@techx.vcet.edu.in',
    name: 'Rohan Mehta',
    department: 'IT',
    completedProducts: [...ALL_PRODUCT_IDS],
    unlockedLabs: ['a', 'c', 'd', 'e'],
    completedLabs: ['a', 'c', 'd', 'e'],
    shards: ['a', 'c', 'd', 'e'],
    discoveredClues: ['clue-c-2'],
    discoveredTreasures: ['tr-map'],
  },
  {
    email: 'ananya.iyer@techx.vcet.edu.in',
    name: 'Ananya Iyer',
    department: 'EXTC',
    completedProducts: [
      '502-01', '502-02', '502-03', '502-04', '502-05',
      '508-01', '508-02', '508-03',
      '509-01', '509-02', '509-03',
    ],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: ['clue-a-1'],
    discoveredTreasures: ['tr-coin'],
  },
  {
    email: 'siddharth.verma@techx.vcet.edu.in',
    name: 'Siddharth Verma',
    department: 'MECH',
    completedProducts: [
      '502-01', '502-02', '502-03',
      '508-01', '508-02', '508-03',
      '509-01', '509-02',
    ],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: ['clue-a-2'],
    discoveredTreasures: [],
  },
  {
    email: 'tanvi.kulkarni@techx.vcet.edu.in',
    name: 'Tanvi Kulkarni',
    department: 'AI-DS',
    completedProducts: [
      '502-01', '502-02', '502-03', '502-04', '502-05', '502-06', '502-07', '502-08', '502-09', '502-10',
      '508-01', '508-02',
    ],
    unlockedLabs: ['a', 'c'],
    completedLabs: ['a'],
    shards: ['a'],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'aditya.joshi@techx.vcet.edu.in',
    name: 'Aditya Joshi',
    department: 'COMPS',
    completedProducts: [
      '502-01', '502-04', '502-05',
      '508-02', '508-03',
      '509-01', '509-04',
    ],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'ishaan.nair@techx.vcet.edu.in',
    name: 'Ishaan Nair',
    department: 'IT',
    completedProducts: ['502-01', '502-02', '508-01', '508-02', '509-01', '509-02'],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'sneha.deshmukh@techx.vcet.edu.in',
    name: 'Sneha Deshmukh',
    department: 'EXTC',
    completedProducts: ['502-02', '502-04', '508-04', '509-04', '509-05'],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'varun.gupta@techx.vcet.edu.in',
    name: 'Varun Gupta',
    department: 'AI-DS',
    completedProducts: ['502-01', '502-03', '508-01', '509-03', '509-06'],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
];

export const defaultFeedback: FeedbackEntry[] = [
  // --- Lab 502 (Sector 1 / a) ---
  {
    _id: 'fb-1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'a',
    tableId: '502-01',
    rating: 5,
    comment: 'ASTRON has a sleek interface and instantaneous celestial query response.',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    _id: 'fb-2',
    studentName: 'Diya Patel',
    studentEmail: 'diya.patel@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'a',
    tableId: '502-02',
    rating: 5,
    comment: 'MAITRI community assistive intelligence is thoughtful and easy to navigate.',
    timestamp: new Date(Date.now() - 3400000).toISOString(),
    createdAt: new Date(Date.now() - 3400000),
  },
  {
    _id: 'fb-3',
    studentName: 'Rohan Mehta',
    studentEmail: 'rohan.mehta@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'a',
    tableId: '502-03',
    rating: 5,
    comment: 'ROBOT autonomous obstacle avoidance and motor agility are outstanding.',
    timestamp: new Date(Date.now() - 3200000).toISOString(),
    createdAt: new Date(Date.now() - 3200000),
  },
  {
    _id: 'fb-4',
    studentName: 'Ananya Iyer',
    studentEmail: 'ananya.iyer@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'a',
    tableId: '502-04',
    rating: 4,
    comment: 'LEARNAIMO gamified education module makes complex concepts fun.',
    timestamp: new Date(Date.now() - 3000000).toISOString(),
    createdAt: new Date(Date.now() - 3000000),
  },
  {
    _id: 'fb-5',
    studentName: 'Siddharth Verma',
    studentEmail: 'siddharth.verma@techx.vcet.edu.in',
    studentDepartment: 'MECH',
    labId: 'a',
    tableId: '502-05',
    rating: 5,
    comment: 'AVG endpoint threat telemetry and shield protection work rapidly.',
    timestamp: new Date(Date.now() - 2800000).toISOString(),
    createdAt: new Date(Date.now() - 2800000),
  },
  {
    _id: 'fb-6',
    studentName: 'Tanvi Kulkarni',
    studentEmail: 'tanvi.kulkarni@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'a',
    tableId: '502-06',
    rating: 5,
    comment: 'BYTEVERSE spatial 3D virtual environment has stellar visual shaders.',
    timestamp: new Date(Date.now() - 2600000).toISOString(),
    createdAt: new Date(Date.now() - 2600000),
  },
  {
    _id: 'fb-7',
    studentName: 'Aditya Joshi',
    studentEmail: 'aditya.joshi@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'a',
    tableId: '502-07',
    rating: 4,
    comment: 'IN-OUT DESK biometric workstation sensors work smoothly.',
    timestamp: new Date(Date.now() - 2400000).toISOString(),
    createdAt: new Date(Date.now() - 2400000),
  },
  {
    _id: 'fb-8',
    studentName: 'Ishaan Nair',
    studentEmail: 'ishaan.nair@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'a',
    tableId: '502-08',
    rating: 5,
    comment: 'LED LIGHT frequency modulation hardware demonstration was clear.',
    timestamp: new Date(Date.now() - 2200000).toISOString(),
    createdAt: new Date(Date.now() - 2200000),
  },
  {
    _id: 'fb-9',
    studentName: 'Sneha Deshmukh',
    studentEmail: 'sneha.deshmukh@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'a',
    tableId: '502-09',
    rating: 5,
    comment: 'FODUU interactive web solution architecture is very clean.',
    timestamp: new Date(Date.now() - 2100000).toISOString(),
    createdAt: new Date(Date.now() - 2100000),
  },
  {
    _id: 'fb-10',
    studentName: 'Varun Gupta',
    studentEmail: 'varun.gupta@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'a',
    tableId: '502-10',
    rating: 5,
    comment: 'MEND-X medical triage diagnostic assistant has brilliant accuracy.',
    timestamp: new Date(Date.now() - 2000000).toISOString(),
    createdAt: new Date(Date.now() - 2000000),
  },

  // --- Lab 508 (Sector 2 / c) ---
  {
    _id: 'fb-11',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'c',
    tableId: '508-01',
    rating: 5,
    comment: 'SYNERGY AUTOMATION industrial smart workflows are seamlessly orchestrated.',
    timestamp: new Date(Date.now() - 1900000).toISOString(),
    createdAt: new Date(Date.now() - 1900000),
  },
  {
    _id: 'fb-12',
    studentName: 'Diya Patel',
    studentEmail: 'diya.patel@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'c',
    tableId: '508-02',
    rating: 5,
    comment: 'TECH SAI CARE medical telemetry and diagnostic charts are crisp.',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    createdAt: new Date(Date.now() - 1800000),
  },
  {
    _id: 'fb-13',
    studentName: 'Rohan Mehta',
    studentEmail: 'rohan.mehta@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'c',
    tableId: '508-03',
    rating: 5,
    comment: 'DEUEX dual-display setup is highly convenient and responsive.',
    timestamp: new Date(Date.now() - 1700000).toISOString(),
    createdAt: new Date(Date.now() - 1700000),
  },
  {
    _id: 'fb-14',
    studentName: 'Sneha Deshmukh',
    studentEmail: 'sneha.deshmukh@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'c',
    tableId: '508-04',
    rating: 4,
    comment: 'GLOBALNET distributed routing shows great packet throughput.',
    timestamp: new Date(Date.now() - 1600000).toISOString(),
    createdAt: new Date(Date.now() - 1600000),
  },
  {
    _id: 'fb-15',
    studentName: 'Siddharth Verma',
    studentEmail: 'siddharth.verma@techx.vcet.edu.in',
    studentDepartment: 'MECH',
    labId: 'c',
    tableId: '508-05',
    rating: 4,
    comment: 'TECH CRYPTERS cryptographic ledger security verification was solid.',
    timestamp: new Date(Date.now() - 1500000).toISOString(),
    createdAt: new Date(Date.now() - 1500000),
  },
  {
    _id: 'fb-16',
    studentName: 'Varun Gupta',
    studentEmail: 'varun.gupta@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'c',
    tableId: '508-06',
    rating: 5,
    comment: 'MICROSOFT POWER AUTOMATE robotic triggers fired without latency.',
    timestamp: new Date(Date.now() - 1400000).toISOString(),
    createdAt: new Date(Date.now() - 1400000),
  },

  // --- Lab 509 (Sector 3 / d) ---
  {
    _id: 'fb-17',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'd',
    tableId: '509-01',
    rating: 5,
    comment: 'PAPERPAL academic writing suggestions are refined and contextual.',
    timestamp: new Date(Date.now() - 1300000).toISOString(),
    createdAt: new Date(Date.now() - 1300000),
  },
  {
    _id: 'fb-18',
    studentName: 'Diya Patel',
    studentEmail: 'diya.patel@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'd',
    tableId: '509-02',
    rating: 5,
    comment: 'R DISCOVERY scholarly paper recommendations saved immense literature review time.',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    createdAt: new Date(Date.now() - 1200000),
  },
  {
    _id: 'fb-19',
    studentName: 'Rohan Mehta',
    studentEmail: 'rohan.mehta@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'd',
    tableId: '509-03',
    rating: 5,
    comment: 'ASSETORBIT telemetry tracking dashboard is responsive and informative.',
    timestamp: new Date(Date.now() - 1100000).toISOString(),
    createdAt: new Date(Date.now() - 1100000),
  },
  {
    _id: 'fb-20',
    studentName: 'Ananya Iyer',
    studentEmail: 'ananya.iyer@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'd',
    tableId: '509-04',
    rating: 5,
    comment: 'SYNKARO data synchronization across channels had zero race conditions.',
    timestamp: new Date(Date.now() - 1000000).toISOString(),
    createdAt: new Date(Date.now() - 1000000),
  },
  {
    _id: 'fb-21',
    studentName: 'Siddharth Verma',
    studentEmail: 'siddharth.verma@techx.vcet.edu.in',
    studentDepartment: 'MECH',
    labId: 'd',
    tableId: '509-05',
    rating: 5,
    comment: 'ABCD IT SOLUTIONS enterprise solutions architecture is clean and robust.',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    createdAt: new Date(Date.now() - 900000),
  },
  {
    _id: 'fb-22',
    studentName: 'Aditya Joshi',
    studentEmail: 'aditya.joshi@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'd',
    tableId: '509-06',
    rating: 4,
    comment: 'SETH COMPUTERS hardware rig benchmarks hit maximum clock speeds.',
    timestamp: new Date(Date.now() - 800000).toISOString(),
    createdAt: new Date(Date.now() - 800000),
  },
  {
    _id: 'fb-23',
    studentName: 'Varun Gupta',
    studentEmail: 'varun.gupta@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'd',
    tableId: '509-07',
    rating: 4,
    comment: 'ANAY IT SOLUTIONS agile business analytics were well presented.',
    timestamp: new Date(Date.now() - 700000).toISOString(),
    createdAt: new Date(Date.now() - 700000),
  },
  {
    _id: 'fb-24',
    studentName: 'Tanvi Kulkarni',
    studentEmail: 'tanvi.kulkarni@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'd',
    tableId: '509-08',
    rating: 5,
    comment: 'SHIVAM STOCK real-time portfolio analytics gave crystal-clear metrics.',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    createdAt: new Date(Date.now() - 600000),
  },
  {
    _id: 'fb-25',
    studentName: 'Ishaan Nair',
    studentEmail: 'ishaan.nair@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'd',
    tableId: '509-09',
    rating: 5,
    comment: 'SAMSUNG ECOSYSTEMS cross-device interconnectivity was seamless.',
    timestamp: new Date(Date.now() - 550000).toISOString(),
    createdAt: new Date(Date.now() - 550000),
  },
  {
    _id: 'fb-26',
    studentName: 'Sneha Deshmukh',
    studentEmail: 'sneha.deshmukh@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'd',
    tableId: '509-10',
    rating: 5,
    comment: 'IOS SYSTEM user experience and UI fluidness were outstanding.',
    timestamp: new Date(Date.now() - 500000).toISOString(),
    createdAt: new Date(Date.now() - 500000),
  },

  // --- Lab 510 (Sector 4 / e) ---
  {
    _id: 'fb-27',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'e',
    tableId: '510-01',
    rating: 5,
    comment: 'MICROSOFT ACCESS rapid relational data inventory was straightforward and fast.',
    timestamp: new Date(Date.now() - 400000).toISOString(),
    createdAt: new Date(Date.now() - 400000),
  },
  {
    _id: 'fb-28',
    studentName: 'Diya Patel',
    studentEmail: 'diya.patel@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'e',
    tableId: '510-02',
    rating: 5,
    comment: 'ADSNEX AI neural predictive marketing algorithms demonstrated pinpoint accuracy.',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    createdAt: new Date(Date.now() - 300000),
  },
  {
    _id: 'fb-29',
    studentName: 'Rohan Mehta',
    studentEmail: 'rohan.mehta@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'e',
    tableId: '510-03',
    rating: 5,
    comment: 'META GLASSES spatial augmented reality computing was the highlight of the event!',
    timestamp: new Date(Date.now() - 200000).toISOString(),
    createdAt: new Date(Date.now() - 200000),
  },
  {
    _id: 'fb-30',
    studentName: 'Ananya Iyer',
    studentEmail: 'ananya.iyer@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'e',
    tableId: '510-04',
    rating: 5,
    comment: 'OPTINEX optical low-latency routing gateway demonstrated top benchmark speeds.',
    timestamp: new Date(Date.now() - 100000).toISOString(),
    createdAt: new Date(Date.now() - 100000),
  },
];
