// Uncharted Expedition — seed data shared by the in-memory store and the
// MongoDB store (seeded once when both collections are empty).

import { FeedbackEntry, ExpeditionUser } from './models';

export const defaultUsers: ExpeditionUser[] = [
  {
    email: 'aarav.sharma@techx.vcet.edu.in',
    name: 'Aarav Sharma',
    department: 'AI-DS',
    completedProducts: [
      'c1-p1', 'c1-p2', 'c1-p3', 'c1-p4', 'c1-p5', 'c1-p6', 'c1-p7', 'c1-p8', 'c1-p9', 'c1-p10',
      'c2-p1', 'c2-p2', 'c2-p3', 'c2-p4', 'c2-p5',
      'c3-p1', 'c3-p2', 'c3-p3', 'c3-p4', 'c3-p5', 'c3-p6', 'c3-p7', 'c3-p8', 'c3-p9', 'c3-p10',
      'c4-p1', 'c4-p2', 'c4-p3', 'c4-p4', 'c4-p5'
    ],
    unlockedLabs: ['a', 'c', 'd', 'e'],
    completedLabs: ['a', 'c', 'd', 'e'],
    shards: ['a', 'c', 'd', 'e'],
    discoveredClues: ['clue-a-1'],
    discoveredTreasures: ['tr-coin'],
  },
  {
    email: 'diya.patel@techx.vcet.edu.in',
    name: 'Diya Patel',
    department: 'COMPS',
    completedProducts: [
      'c1-p1', 'c1-p2', 'c1-p3', 'c1-p4', 'c1-p5', 'c1-p6', 'c1-p7', 'c1-p8', 'c1-p9', 'c1-p10',
      'c2-p1', 'c2-p2', 'c2-p3', 'c2-p4', 'c2-p5',
      'c3-p1', 'c3-p2', 'c3-p3', 'c3-p4', 'c3-p5', 'c3-p6', 'c3-p7', 'c3-p8', 'c3-p9', 'c3-p10',
      'c4-p1', 'c4-p2', 'c4-p3', 'c4-p4', 'c4-p5'
    ],
    unlockedLabs: ['a', 'c', 'd', 'e'],
    completedLabs: ['a', 'c', 'd', 'e'],
    shards: ['a', 'c', 'd', 'e'],
    discoveredClues: ['clue-a-2'],
    discoveredTreasures: ['tr-relic'],
  },
  {
    email: 'rohan.mehta@techx.vcet.edu.in',
    name: 'Rohan Mehta',
    department: 'IT',
    completedProducts: [
      'c1-p1', 'c1-p2', 'c1-p3', 'c1-p4', 'c1-p5', 'c1-p6', 'c1-p7', 'c1-p8', 'c1-p9', 'c1-p10',
      'c2-p1', 'c2-p2', 'c2-p3', 'c2-p4', 'c2-p5',
      'c3-p1', 'c3-p2', 'c3-p3', 'c3-p4', 'c3-p5', 'c3-p6', 'c3-p7', 'c3-p8', 'c3-p9', 'c3-p10',
      'c4-p1', 'c4-p2', 'c4-p3', 'c4-p4', 'c4-p5'
    ],
    unlockedLabs: ['a', 'c', 'd', 'e'],
    completedLabs: ['a', 'c', 'd', 'e'],
    shards: ['a', 'c', 'd', 'e'],
    discoveredClues: ['clue-c-2'],
    discoveredTreasures: ['tr-map'],
  },
  {
    email: 'ananya.iyer@techx.vcet.edu.in',
    name: 'Ananya Iyer',
    department: 'EXTC',
    completedProducts: [
      'c1-p1', 'c1-p2', 'c1-p3', 'c1-p4', 'c1-p5',
      'c2-p1', 'c2-p2', 'c2-p3', 'c2-p4',
      'c3-p1', 'c3-p2', 'c3-p3', 'c3-p4', 'c3-p5'
    ],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: ['clue-a-1'],
    discoveredTreasures: ['tr-coin'],
  },
  {
    email: 'siddharth.verma@techx.vcet.edu.in',
    name: 'Siddharth Verma',
    department: 'MECH',
    completedProducts: [
      'c1-p1', 'c1-p2', 'c1-p3',
      'c2-p1', 'c2-p2', 'c2-p3', 'c2-p4',
      'c3-p1', 'c3-p2', 'c3-p3', 'c3-p4'
    ],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: ['clue-a-2'],
    discoveredTreasures: [],
  },
  {
    email: 'tanvi.kulkarni@techx.vcet.edu.in',
    name: 'Tanvi Kulkarni',
    department: 'AI-DS',
    completedProducts: [
      'c1-p1', 'c1-p2', 'c1-p3', 'c1-p4', 'c1-p5', 'c1-p6', 'c1-p7', 'c1-p8', 'c1-p9', 'c1-p10',
      'c2-p1', 'c2-p2'
    ],
    unlockedLabs: ['a', 'c'],
    completedLabs: ['a'],
    shards: ['a'],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'aditya.joshi@techx.vcet.edu.in',
    name: 'Aditya Joshi',
    department: 'COMPS',
    completedProducts: [
      'c1-p1', 'c1-p4', 'c1-p5',
      'c2-p2', 'c2-p3',
      'c3-p1', 'c3-p4', 'c3-p5'
    ],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'ishaan.nair@techx.vcet.edu.in',
    name: 'Ishaan Nair',
    department: 'IT',
    completedProducts: ['c1-p1', 'c1-p2', 'c2-p1', 'c2-p2', 'c3-p1', 'c3-p2'],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'sneha.deshmukh@techx.vcet.edu.in',
    name: 'Sneha Deshmukh',
    department: 'EXTC',
    completedProducts: ['c1-p2', 'c1-p4', 'c2-p4', 'c3-p4', 'c3-p5'],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
  {
    email: 'varun.gupta@techx.vcet.edu.in',
    name: 'Varun Gupta',
    department: 'AI-DS',
    completedProducts: ['c1-p1', 'c1-p3', 'c2-p1', 'c3-p3', 'c3-p6'],
    unlockedLabs: ['a', 'c', 'd'],
    completedLabs: [],
    shards: [],
    discoveredClues: [],
    discoveredTreasures: [],
  },
];

export const defaultFeedback: FeedbackEntry[] = [
  // --- Lab 502 (Sector 1 / a) ---
  {
    _id: 'fb-1',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'a',
    tableId: 'c1-p1',
    rating: 5,
    comment: 'ASSETORBIT has a sleek interface and instantaneous query response.',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    _id: 'fb-2',
    studentName: 'Diya Patel',
    studentEmail: 'diya.patel@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'a',
    tableId: 'c1-p1',
    rating: 5,
    comment: 'Exceptional real-time orbital tracking and clean dashboard UI.',
    timestamp: new Date(Date.now() - 3400000).toISOString(),
    createdAt: new Date(Date.now() - 3400000),
  },
  {
    _id: 'fb-3',
    studentName: 'Rohan Mehta',
    studentEmail: 'rohan.mehta@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'a',
    tableId: 'c1-p2',
    rating: 5,
    comment: 'SUNTECH TECHNOLOGY provides impressive solar telemetry models.',
    timestamp: new Date(Date.now() - 3200000).toISOString(),
    createdAt: new Date(Date.now() - 3200000),
  },
  {
    _id: 'fb-4',
    studentName: 'Ananya Iyer',
    studentEmail: 'ananya.iyer@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'a',
    tableId: 'c1-p3',
    rating: 4,
    comment: 'ABCD IT SOLUTIONS has robust enterprise architecture and clean code.',
    timestamp: new Date(Date.now() - 3000000).toISOString(),
    createdAt: new Date(Date.now() - 3000000),
  },
  {
    _id: 'fb-5',
    studentName: 'Siddharth Verma',
    studentEmail: 'siddharth.verma@techx.vcet.edu.in',
    studentDepartment: 'MECH',
    labId: 'a',
    tableId: 'c1-p4',
    rating: 5,
    comment: 'ADSNEX AI shows remarkable precision in algorithmic targeting.',
    timestamp: new Date(Date.now() - 2800000).toISOString(),
    createdAt: new Date(Date.now() - 2800000),
  },
  {
    _id: 'fb-6',
    studentName: 'Tanvi Kulkarni',
    studentEmail: 'tanvi.kulkarni@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'a',
    tableId: 'c1-p5',
    rating: 5,
    comment: 'META GLASSES AR capabilities and spatial computing are mind-blowing.',
    timestamp: new Date(Date.now() - 2600000).toISOString(),
    createdAt: new Date(Date.now() - 2600000),
  },
  {
    _id: 'fb-7',
    studentName: 'Aditya Joshi',
    studentEmail: 'aditya.joshi@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'a',
    tableId: 'c1-p6',
    rating: 4,
    comment: 'OPTINEXT GLOBAL.IN demonstrates great low-latency optical routing.',
    timestamp: new Date(Date.now() - 2400000).toISOString(),
    createdAt: new Date(Date.now() - 2400000),
  },
  {
    _id: 'fb-8',
    studentName: 'Ishaan Nair',
    studentEmail: 'ishaan.nair@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'a',
    tableId: 'c1-p7',
    rating: 5,
    comment: 'PRELAUNCH is a well thought-out platform for release management.',
    timestamp: new Date(Date.now() - 2200000).toISOString(),
    createdAt: new Date(Date.now() - 2200000),
  },

  // --- Lab 508 (Sector 2 / c) ---
  {
    _id: 'fb-9',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'c',
    tableId: 'c2-p1',
    rating: 5,
    comment: 'MAITRI community assistant is very helpful and empathetic.',
    timestamp: new Date(Date.now() - 2000000).toISOString(),
    createdAt: new Date(Date.now() - 2000000),
  },
  {
    _id: 'fb-10',
    studentName: 'Diya Patel',
    studentEmail: 'diya.patel@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'c',
    tableId: 'c2-p2',
    rating: 5,
    comment: 'R DISCOVERY paper synthesis saves enormous research hours.',
    timestamp: new Date(Date.now() - 1900000).toISOString(),
    createdAt: new Date(Date.now() - 1900000),
  },
  {
    _id: 'fb-11',
    studentName: 'Rohan Mehta',
    studentEmail: 'rohan.mehta@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'c',
    tableId: 'c2-p3',
    rating: 5,
    comment: 'PAPERPAL provides top-notch real-time academic grammar checking.',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    createdAt: new Date(Date.now() - 1800000),
  },
  {
    _id: 'fb-12',
    studentName: 'Sneha Deshmukh',
    studentEmail: 'sneha.deshmukh@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'c',
    tableId: 'c2-p4',
    rating: 4,
    comment: 'LED LIGHT (frequency) demonstrates neat hardware modulation.',
    timestamp: new Date(Date.now() - 1700000).toISOString(),
    createdAt: new Date(Date.now() - 1700000),
  },
  {
    _id: 'fb-13',
    studentName: 'Siddharth Verma',
    studentEmail: 'siddharth.verma@techx.vcet.edu.in',
    studentDepartment: 'MECH',
    labId: 'c',
    tableId: 'c2-p5',
    rating: 4,
    comment: 'SETH COMPUTERS custom rigs deliver fantastic benchmark throughput.',
    timestamp: new Date(Date.now() - 1600000).toISOString(),
    createdAt: new Date(Date.now() - 1600000),
  },
  {
    _id: 'fb-14',
    studentName: 'Varun Gupta',
    studentEmail: 'varun.gupta@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'c',
    tableId: 'c2-p6',
    rating: 4,
    comment: 'ANAY IT SOLUTIONS analytics pipeline runs smoothly.',
    timestamp: new Date(Date.now() - 1500000).toISOString(),
    createdAt: new Date(Date.now() - 1500000),
  },
  {
    _id: 'fb-15',
    studentName: 'Tanvi Kulkarni',
    studentEmail: 'tanvi.kulkarni@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'c',
    tableId: 'c2-p7',
    rating: 5,
    comment: 'SHIVAM STOCKS algorithmic predictions are surprisingly accurate.',
    timestamp: new Date(Date.now() - 1400000).toISOString(),
    createdAt: new Date(Date.now() - 1400000),
  },

  // --- Lab 509 (Sector 3 / d) ---
  {
    _id: 'fb-16',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'd',
    tableId: 'c3-p1',
    rating: 5,
    comment: 'SAMSUNG ECOSYSTEM cross-device synchronization is effortless.',
    timestamp: new Date(Date.now() - 1300000).toISOString(),
    createdAt: new Date(Date.now() - 1300000),
  },
  {
    _id: 'fb-17',
    studentName: 'Diya Patel',
    studentEmail: 'diya.patel@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'd',
    tableId: 'c3-p2',
    rating: 5,
    comment: 'ios project has fluid animations and native Swift responsiveness.',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    createdAt: new Date(Date.now() - 1200000),
  },
  {
    _id: 'fb-18',
    studentName: 'Rohan Mehta',
    studentEmail: 'rohan.mehta@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'd',
    tableId: 'c3-p3',
    rating: 4,
    comment: 'AVG endpoint telemetry is thorough and detected anomalies promptly.',
    timestamp: new Date(Date.now() - 1100000).toISOString(),
    createdAt: new Date(Date.now() - 1100000),
  },
  {
    _id: 'fb-19',
    studentName: 'Ananya Iyer',
    studentEmail: 'ananya.iyer@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'd',
    tableId: 'c3-p4',
    rating: 5,
    comment: 'Robotic arm inverse kinematics and smooth motor control impressed me.',
    timestamp: new Date(Date.now() - 1000000).toISOString(),
    createdAt: new Date(Date.now() - 1000000),
  },
  {
    _id: 'fb-20',
    studentName: 'Siddharth Verma',
    studentEmail: 'siddharth.verma@techx.vcet.edu.in',
    studentDepartment: 'MECH',
    labId: 'd',
    tableId: 'c3-p5',
    rating: 5,
    comment: 'robot navigation with LIDAR avoidance executed cleanly around obstacles.',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    createdAt: new Date(Date.now() - 900000),
  },
  {
    _id: 'fb-21',
    studentName: 'Aditya Joshi',
    studentEmail: 'aditya.joshi@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'd',
    tableId: 'c3-p6',
    rating: 4,
    comment: 'Byteverse 3D spatial space has great shaders and high FPS.',
    timestamp: new Date(Date.now() - 800000).toISOString(),
    createdAt: new Date(Date.now() - 800000),
  },
  {
    _id: 'fb-22',
    studentName: 'Varun Gupta',
    studentEmail: 'varun.gupta@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'd',
    tableId: 'c3-p7',
    rating: 4,
    comment: 'In-Out Desk biometric sensor integration is very practical.',
    timestamp: new Date(Date.now() - 700000).toISOString(),
    createdAt: new Date(Date.now() - 700000),
  },
  {
    _id: 'fb-23',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'd',
    tableId: 'c3-p8',
    rating: 5,
    comment: 'Mend-x digital medical assistant has great diagnostic guidance.',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    createdAt: new Date(Date.now() - 600000),
  },

  // --- Lab 510 (Sector 4 / e) ---
  {
    _id: 'fb-24',
    studentName: 'Aarav Sharma',
    studentEmail: 'aarav.sharma@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'e',
    tableId: 'c4-p1',
    rating: 5,
    comment: 'SANDSTORM AI neural vision handled low-visibility dust simulations amazingly.',
    timestamp: new Date(Date.now() - 500000).toISOString(),
    createdAt: new Date(Date.now() - 500000),
  },
  {
    _id: 'fb-25',
    studentName: 'Diya Patel',
    studentEmail: 'diya.patel@techx.vcet.edu.in',
    studentDepartment: 'COMPS',
    labId: 'e',
    tableId: 'c4-p2',
    rating: 5,
    comment: 'SOLARIS GRID energy dispatch telemetry was very responsive and well designed.',
    timestamp: new Date(Date.now() - 400000).toISOString(),
    createdAt: new Date(Date.now() - 400000),
  },
  {
    _id: 'fb-26',
    studentName: 'Rohan Mehta',
    studentEmail: 'rohan.mehta@techx.vcet.edu.in',
    studentDepartment: 'IT',
    labId: 'e',
    tableId: 'c4-p3',
    rating: 4,
    comment: 'DUNE ROVER ROBOTICS suspension mechanics and obstacle routing were solid.',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    createdAt: new Date(Date.now() - 300000),
  },
  {
    _id: 'fb-27',
    studentName: 'Ananya Iyer',
    studentEmail: 'ananya.iyer@techx.vcet.edu.in',
    studentDepartment: 'EXTC',
    labId: 'e',
    tableId: 'c4-p4',
    rating: 5,
    comment: 'MIRAGE CYBER DEFENSE honeypot architecture gave immediate intrusion telemetry.',
    timestamp: new Date(Date.now() - 200000).toISOString(),
    createdAt: new Date(Date.now() - 200000),
  },
  {
    _id: 'fb-28',
    studentName: 'Siddharth Verma',
    studentEmail: 'siddharth.verma@techx.vcet.edu.in',
    studentDepartment: 'MECH',
    labId: 'e',
    tableId: 'c4-p5',
    rating: 5,
    comment: 'OASIS HYDRATION IOT sensor telemetry and filtration controls are innovative.',
    timestamp: new Date(Date.now() - 150000).toISOString(),
    createdAt: new Date(Date.now() - 150000),
  },
  {
    _id: 'fb-29',
    studentName: 'Tanvi Kulkarni',
    studentEmail: 'tanvi.kulkarni@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'e',
    tableId: 'c4-p6',
    rating: 5,
    comment: 'PYRAMID CLOUD distributed storage protocol has high fault tolerance.',
    timestamp: new Date(Date.now() - 100000).toISOString(),
    createdAt: new Date(Date.now() - 100000),
  },
  {
    _id: 'fb-30',
    studentName: 'Varun Gupta',
    studentEmail: 'varun.gupta@techx.vcet.edu.in',
    studentDepartment: 'AI-DS',
    labId: 'e',
    tableId: 'c4-p7',
    rating: 5,
    comment: 'SCARAB SENSORS mesh network synchronization across large radii worked flawlessly.',
    timestamp: new Date(Date.now() - 50000).toISOString(),
    createdAt: new Date(Date.now() - 50000),
  },
];
